Feature - Search - Implement API
blkbrds/intern16_final_project_ThinhNguyenP pull request #17
Opened 2020-09-10 08:55 UTC by at-thinhnguyen6

2020-09-18 13:48 UTC, at-vanle commented on TheRestaurants/Model/Scheme/SearchHistory.swift
> -
WARNING - Please insert empty after type declaration.

2020-09-18 13:48 UTC, at-vanle commented on TheRestaurants/View/Search/HistorySearch/HistorySearchCellModel.swift
> -
WARNING - Please insert empty after type declaration.

2020-09-18 13:48 UTC, at-vanle commented on TheRestaurants/View/Search/SearchViewModel.swift
>  class SearchViewModel {
WARNING - Please insert empty after type declaration.

2020-09-18 13:48 UTC, at-vanle commented on TheRestaurants/View/Search/SearchViewModel.swift
> -            return history.count
WARNING - Opening braces should be preceded by a single space and on the same line as the declaration.

2020-09-18 13:48 UTC, at-vanle commented on TheRestaurants/View/Search/ResultSearch/SearchResultCell.swift
> +
WARNING - Lines should not have trailing whitespace.

2020-09-18 13:48 UTC, at-vanle commented on TheRestaurants/View/Search/ResultSearch/SearchResultCellModel.swift
> +class SearchResultCellModel {
WARNING - Please insert empty after type declaration.

2020-09-18 13:48 UTC, at-vanle commented on TheRestaurants/View/Search/ResultSearch/SearchResultCellModel.swift
> +
WARNING - Lines should not have trailing whitespace.

2020-09-18 13:48 UTC, at-vanle commented
Total linter violations in pull request: 7
Serious: 0
Warnings: 7

2020-09-20 17:38 UTC, at-vanle commented on TheRestaurants/View/Search/SearchViewController.swift
>          case .historySearch:
WARNING - Closure expressions should have a single space inside each brace.

2020-09-20 17:38 UTC, at-vanle commented on TheRestaurants/View/Search/SearchViewController.swift
>              textfield.placeholder = "Tìm kiếm địa điểm "
WARNING - Line should be 132 characters or less: currently 170 characters

2020-09-20 17:38 UTC, at-vanle commented on TheRestaurants/View/Search/SearchViewController.swift
>          case .historySearch:
WARNING - Line should be 132 characters or less: currently 160 characters

2020-09-20 17:38 UTC, at-vanle commented on TheRestaurants/View/Search/SearchViewController.swift
> +            cell.viewModel = viewModel.viewModelForCellHistoried(at: indexPath)
WARNING - Line should be 132 characters or less: currently 151 characters

2020-09-23 11:00 UTC, at-vanle commented on TheRestaurants/View/Search/SearchViewController.swift
> -        switch viewModel.search[indexPath.row] {
WARNING - Line should be 132 characters or less: currently 147 characters

2020-09-23 11:00 UTC, at-vanle commented
Total linter violations in pull request: 18
Serious: 0
Warnings: 18

2020-09-24 00:35 UTC, at-vanle commented on TheRestaurants/View/Search/SearchViewController.swift
>      }
WARNING - Line should be 132 characters or less: currently 134 characters

2020-09-24 00:35 UTC, at-vanle commented on TheRestaurants/View/Search/SearchViewController.swift
> +        if tableView == listResultSearch {
WARNING - Line should be 132 characters or less: currently 134 characters

2020-09-24 00:35 UTC, at-vanle commented on TheRestaurants/View/Search/SearchViewModel.swift
> +            try realm.write {
WARNING - Must have an empty line between functions.

2020-09-24 00:35 UTC, at-vanle commented
Total linter violations in pull request: 13
Serious: 0
Warnings: 13

2020-09-24 03:59 UTC, at-vanle commented
Total linter violations in pull request: 12
Serious: 0
Warnings: 12

2020-09-24 04:25 UTC, at-vanle requested changes
@at-thinhnguyen6 Please check my comments. Thanks!

2020-09-24 04:25 UTC, at-vanle commented on TheRestaurants/Model/API/Api.Search.swift
> +                        guard let restaurant = item["restaurant"] as? JSObject,
```suggestion
                        guard let json = item["restaurant"] as? JSObject,
```

2020-09-24 04:25 UTC, at-vanle commented on TheRestaurants/Model/API/Api.Search.swift
> +                        let restaurant2 = Mapper<Restaurant>().map(JSONObject: restaurant) else { return }
```suggestion
                        let restaurant = Mapper<Restaurant>().map(JSONObject: restaurant) else { return }
```

2020-09-24 04:25 UTC, at-vanle commented on TheRestaurants/Model/Scheme/Restaurant.swift
> +import RealmSwift
Import mà không dùng à?

2020-09-24 04:25 UTC, at-vanle commented on TheRestaurants/View/Search/ResultSearch/SearchResultCell.swift
> +class SearchResultCell: UITableViewCell {
Đã nói là dùng Home Cell rồi mà?

2020-09-24 04:25 UTC, at-vanle commented on TheRestaurants/View/Search/ResultSearch/SearchResultCellModel.swift
> +class SearchResultCellModel {
Dùng HomeCell

2020-09-24 04:25 UTC, at-vanle commented on TheRestaurants/View/Search/SearchViewController.swift
> +    private func addRealm(searchKey: String) {
```suggestion
    private func saveKeyToRealm(searchKey: String) {
```

2020-09-24 04:25 UTC, at-vanle commented on TheRestaurants/View/Search/SearchViewController.swift
> +                this.fetchData()
Gì đây? Để làm gì?

2020-09-24 04:25 UTC, at-vanle commented on TheRestaurants/View/Search/SearchViewController.swift
>      @IBOutlet private weak var listHistoriedSerch: UITableView!
```suggestion
    @IBOutlet private weak var searchHistoryTableView: UITableView!
```

2020-09-24 04:25 UTC, at-vanle commented on TheRestaurants/View/Search/SearchViewController.swift
>      @IBOutlet private weak var listResultSearch: UITableView!
```suggestion
    @IBOutlet private weak var resultTableView: UITableView!
```

2020-09-24 04:25 UTC, at-vanle commented on TheRestaurants/View/Search/SearchViewController.swift
> +            listResultSearch.isHidden = false
Cái này phải xử lý trong completion của hàm **loadCell**

2020-09-24 04:25 UTC, at-vanle commented on TheRestaurants/View/Search/SearchViewController.swift
> +            listHistoriedSerch.isHidden = true
Như trên

2020-09-24 04:25 UTC, at-vanle commented on TheRestaurants/View/Search/SearchViewController.swift
> +    func searchBarShouldEndEditing(_ searchBar: UISearchBar) -> Bool {
Làm gì?

2020-09-24 04:25 UTC, at-vanle commented on TheRestaurants/View/Search/SearchViewModel.swift
> +    private var notificationToken: NotificationToken?
Làm gì đây?

2020-09-24 04:25 UTC, at-vanle commented on TheRestaurants/View/Search/SearchViewModel.swift
>      var search: [Search] = [.resultSearch, .historySearch]
Không thấy dùng

2020-09-24 04:25 UTC, at-vanle commented on TheRestaurants/View/Search/SearchViewModel.swift
> +    func viewModelForCellHistoried(at indexPath: IndexPath) -> HistorySearchCellModel {
```suggestion
    func viewModelForHistoryCell(at indexPath: IndexPath) -> HistorySearchCellModel {
```

2020-09-24 04:25 UTC, at-vanle commented on TheRestaurants/View/Search/SearchViewModel.swift
> +    func viewModelForCellResult(indexPath: IndexPath) -> HomeCellModel {
```suggestion
    func viewModelForResultCell(indexPath: IndexPath) -> HomeCellModel {
```

2020-09-24 04:25 UTC, at-vanle commented on TheRestaurants/View/Search/SearchViewModel.swift
> +            histories = Array((results).reversed().prefix(7))
Chỗ này xử lý sao đây? Vì sao phải **prefix(7)**?

2020-09-24 04:25 UTC, at-vanle commented on TheRestaurants/View/Search/SearchViewModel.swift
> +            print(error)
**completion(.failure(error))**

2020-09-24 04:25 UTC, at-vanle commented on TheRestaurants/View/Search/SearchViewModel.swift
> +    func fetchData(completion: @escaping APICompletion) {
```suggestion
    func fetchSearchHistoryData(completion: @escaping APICompletion) {
```

2020-09-24 04:25 UTC, at-vanle commented on TheRestaurants/View/Search/SearchViewModel.swift
> +    func addRealm(searchKey: String, completion: @escaping APICompletion) {
```suggestion
    func saveKeyToRealm(searchKey: String, completion: @escaping APICompletion) {
```

2020-09-24 05:34 UTC, at-thinhnguyen6 commented on TheRestaurants/View/Search/SearchViewModel.swift
> +            histories = Array((results).reversed().prefix(7))
dạ e muốn lấy 7 cái đầu tiên cho gọn ạ

2020-09-24 05:40 UTC, at-vanle commented
Total linter violations in pull request: 13
Serious: 0
Warnings: 13

2020-09-24 07:05 UTC, at-vanle requested changes
@at-thinhnguyen6 Please check my comments. Thank you!

2020-09-24 07:05 UTC, at-vanle commented on TheRestaurants/View/Search/SearchViewController.swift
> +    func fetchData() {
```suggestion
    func fetchSearchHistoryData() {
```

2020-09-24 10:37 UTC, at-vanle approved these changes
LGTM!

2020-09-24 10:38 UTC, merged